namespace Conjugar.Core.Utils
{
    public static class Listas
    {
        // TODO: Colocar na lista verbos da 4ª conjugação
        public static string[] VerbosIrregulares = {
            "abaular", "abolir","abster","acudir","adequar","advertir","descer","advir","agredir","aguar","aguerrir","ajuizar","amiudar","ansiar","antever","antiquar","apaziguar","apaniguar","aprazer","arguir","arruinar","assentir","augir","averiguar","avir","bem-querer","boiar","bulir","caber","cerzir","cobir","coibir","colorir","comedir","comerciar","compelir","competir","compor","por", "repor", "supor","comprazer","concernir","conseguir","consentir","contruir","consumir","conter","contiguar","contravir","convir","corroer","crer","cuspir","dar","deflectir","demolir","denegrir","desaguar","desavir","descaber","descobrir","desimpedir","desmentir","demiudar","despedir","despir","desprazer","desquerer","destruir","deter","devir","discernir","divergir","divertir","doer","dormir","eclodir","empedernir","encobrir","engolir","enraizar","entreter","entupir","enviuvar","equivaler","esmiucar","esmiuçar","espavorir","estar","estiar","europeixar","expedir","expelir","explodir","fazer","flectir","fremir","fugir","fulgir","haver","hebraizar","homogeneizar","impedir","impelir","incendiar","inflectir","instruir","intermediar","intervir","investir","ir","jazer","judaizar","ler","licenciar","malquerer","manter","mediar","medir","mentir","minguar","moer","mugir","multicolorir","negociar","nevar","obliquar","obsequiar","obstruir","obter","odiar","orvalhar","ouvir","parar","parir","pedir","perder","perseguir","plebeizar","poder","polir","pôr","por","premiar","premir","pressentir","prevenir","prever","progredir","proibir","prosseguir","prover","provir","querer","rebolir","rebulir","reflectir","refulgir","regredir","relampejar","remir","remoer","repelir","repetir","requerer","ressentir","reter","reunir","rever","resentir","revir","rir","roer","rugir","saber","sacudir","saraviar","saudar","seguir","sentir","ser","servir","sorrir","sortir","subir","sumir","suster","ter","tossir","transgredir","trazer","trovejar","tugir","valer","ventar","ver","vestir","vir","viuvar"
        };
    }
}
